apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30080
  type: NodePort # 可以将服务暴露到节点的IP地址和端口上
