apiVersion: apps/v1
kind: Deployment # Deployment就是管理Pod资源的对象
metadata:
  name: gateway # Pod名称
  labels:
    app: gateway # Pod标签 为service提供负载均衡使用
spec:
  replicas: 1 # 副本为1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: micro-todolist-k8s/gateway:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/bin/config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: configmap
          items:
          - key: config.yaml
            path: config.yaml

