apiVersion: v1
kind: Service
metadata:
  name: gateway-promethus-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30994
  type: NodePort
