apiVersion: v1
kind: Service
metadata:
  name: task-promethus-service
spec:
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
      nodePort: 30993
  type: NodePort
