apiVersion: v1
kind: Service
metadata:
  name: user-promethus-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30992
  type: NodePort
